# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatbot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chatbot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x07\x63hatbot\"s\n\x11\x41skChatBotRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0f\n\x07room_id\x18\x02 \x01(\t\x12\x17\n\x0forganization_id\x18\x03 \x01(\t\x12\x15\n\x08room_key\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_room_key\"$\n\x12\x41skChatBotResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"l\n\x1c\x45xtractMeetingSummaryRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x17\n\x0forganization_id\x18\x02 \x01(\t\x12\x15\n\x08room_key\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_room_key\"5\n\x1d\x45xtractMeetingSummaryResponse\x12\x14\n\x0csummary_json\x18\x01 \x01(\t2\xbf\x01\n\x0e\x43hatbotService\x12\x45\n\nAskChatBot\x12\x1a.chatbot.AskChatBotRequest\x1a\x1b.chatbot.AskChatBotResponse\x12\x66\n\x15\x45xtractMeetingSummary\x12%.chatbot.ExtractMeetingSummaryRequest\x1a&.chatbot.ExtractMeetingSummaryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASKCHATBOTREQUEST']._serialized_start=26
  _globals['_ASKCHATBOTREQUEST']._serialized_end=141
  _globals['_ASKCHATBOTRESPONSE']._serialized_start=143
  _globals['_ASKCHATBOTRESPONSE']._serialized_end=179
  _globals['_EXTRACTMEETINGSUMMARYREQUEST']._serialized_start=181
  _globals['_EXTRACTMEETINGSUMMARYREQUEST']._serialized_end=289
  _globals['_EXTRACTMEETINGSUMMARYRESPONSE']._serialized_start=291
  _globals['_EXTRACTMEETINGSUMMARYRESPONSE']._serialized_end=344
  _globals['_CHATBOTSERVICE']._serialized_start=347
  _globals['_CHATBOTSERVICE']._serialized_end=538
# @@protoc_insertion_point(module_scope)
