# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import chatbot_pb2 as chatbot__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chatbot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SemanticServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AskChatBot = channel.unary_unary(
                '/chatbot.SemanticService/AskChatBot',
                request_serializer=chatbot__pb2.AskChatBotRequest.SerializeToString,
                response_deserializer=chatbot__pb2.AskChatBotResponse.FromString,
                _registered_method=True)


class SemanticServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AskChatBot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SemanticServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AskChatBot': grpc.unary_unary_rpc_method_handler(
                    servicer.AskChatBot,
                    request_deserializer=chatbot__pb2.AskChatBotRequest.FromString,
                    response_serializer=chatbot__pb2.AskChatBotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatbot.SemanticService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chatbot.SemanticService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SemanticService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AskChatBot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.SemanticService/AskChatBot',
            chatbot__pb2.AskChatBotRequest.SerializeToString,
            chatbot__pb2.AskChatBotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
