# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatbot.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'chatbot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchatbot.proto\x12\x07\x63hatbot\"6\n\x11\x41skChatBotRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0f\n\x07room_id\x18\x02 \x01(\t\"$\n\x12\x41skChatBotResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t2X\n\x0fSemanticService\x12\x45\n\nAskChatBot\x12\x1a.chatbot.AskChatBotRequest\x1a\x1b.chatbot.AskChatBotResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASKCHATBOTREQUEST']._serialized_start=26
  _globals['_ASKCHATBOTREQUEST']._serialized_end=80
  _globals['_ASKCHATBOTRESPONSE']._serialized_start=82
  _globals['_ASKCHATBOTRESPONSE']._serialized_end=118
  _globals['_SEMANTICSERVICE']._serialized_start=120
  _globals['_SEMANTICSERVICE']._serialized_end=208
# @@protoc_insertion_point(module_scope)
