# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: semantic.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'semantic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esemantic.proto\x12\x08semantic\"\xe7\x01\n\x15SaveTranscriptRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x0f\n\x07speaker\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x16\n\ttimestamp\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08language\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x1c\n\x0forganization_id\x18\x06 \x01(\tH\x02\x88\x01\x01\x12\x15\n\x08room_key\x18\x07 \x01(\tH\x03\x88\x01\x01\x42\x0c\n\n_timestampB\x0b\n\t_languageB\x12\n\x10_organization_idB\x0b\n\t_room_key\":\n\x16SaveTranscriptResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xae\x01\n\x18SearchTranscriptsRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0f\n\x07room_id\x18\x02 \x01(\t\x12\x12\n\x05limit\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12\x1c\n\x0forganization_id\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08room_key\x18\x05 \x01(\tH\x02\x88\x01\x01\x42\x08\n\x06_limitB\x12\n\x10_organization_idB\x0b\n\t_room_key\"H\n\x19SearchTranscriptsResponse\x12+\n\x07results\x18\x01 \x03(\x0b\x32\x1a.semantic.TranscriptResult\"b\n\x10TranscriptResult\x12\x0f\n\x07room_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x12\n\x05score\x18\x04 \x01(\x02H\x00\x88\x01\x01\x42\x08\n\x06_score2\xc4\x01\n\x0fSemanticService\x12S\n\x0eSaveTranscript\x12\x1f.semantic.SaveTranscriptRequest\x1a .semantic.SaveTranscriptResponse\x12\\\n\x11SearchTranscripts\x12\".semantic.SearchTranscriptsRequest\x1a#.semantic.SearchTranscriptsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'semantic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAVETRANSCRIPTREQUEST']._serialized_start=29
  _globals['_SAVETRANSCRIPTREQUEST']._serialized_end=260
  _globals['_SAVETRANSCRIPTRESPONSE']._serialized_start=262
  _globals['_SAVETRANSCRIPTRESPONSE']._serialized_end=320
  _globals['_SEARCHTRANSCRIPTSREQUEST']._serialized_start=323
  _globals['_SEARCHTRANSCRIPTSREQUEST']._serialized_end=497
  _globals['_SEARCHTRANSCRIPTSRESPONSE']._serialized_start=499
  _globals['_SEARCHTRANSCRIPTSRESPONSE']._serialized_end=571
  _globals['_TRANSCRIPTRESULT']._serialized_start=573
  _globals['_TRANSCRIPTRESULT']._serialized_end=671
  _globals['_SEMANTICSERVICE']._serialized_start=674
  _globals['_SEMANTICSERVICE']._serialized_end=870
# @@protoc_insertion_point(module_scope)
