# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import audio_pb2 as audio__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in audio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AllocateTranslationPort = channel.unary_unary(
                '/audio.AudioService/AllocateTranslationPort',
                request_serializer=audio__pb2.PortRequest.SerializeToString,
                response_deserializer=audio__pb2.PortReply.FromString,
                _registered_method=True)
        self.CreateTranslationProduce = channel.unary_unary(
                '/audio.AudioService/CreateTranslationProduce',
                request_serializer=audio__pb2.CreateTranslationCabinRequest.SerializeToString,
                response_deserializer=audio__pb2.CreateTranslationCabinResponse.FromString,
                _registered_method=True)
        self.ProcessAudioBuffer = channel.unary_unary(
                '/audio.AudioService/ProcessAudioBuffer',
                request_serializer=audio__pb2.ProcessAudioBufferRequest.SerializeToString,
                response_deserializer=audio__pb2.ProcessAudioBufferResponse.FromString,
                _registered_method=True)
        self.ProcessAudioChunk = channel.unary_unary(
                '/audio.AudioService/ProcessAudioChunk',
                request_serializer=audio__pb2.ProcessAudioRequest.SerializeToString,
                response_deserializer=audio__pb2.ProcessAudioResponse.FromString,
                _registered_method=True)
        self.GetServiceStats = channel.unary_unary(
                '/audio.AudioService/GetServiceStats',
                request_serializer=audio__pb2.Empty.SerializeToString,
                response_deserializer=audio__pb2.ServiceStatsResponse.FromString,
                _registered_method=True)
        self.DestroyCabin = channel.unary_unary(
                '/audio.AudioService/DestroyCabin',
                request_serializer=audio__pb2.DestroyCabinRequest.SerializeToString,
                response_deserializer=audio__pb2.DestroyCabinResponse.FromString,
                _registered_method=True)


class AudioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AllocateTranslationPort(self, request, context):
        """Translation Cabin methods for B1-B4 flow
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTranslationProduce(self, request, context):
        """Establish a plain RTP connection for audio streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessAudioBuffer(self, request, context):
        """Main audio buffer processing for transcription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessAudioChunk(self, request, context):
        """Legacy audio chunk processing
        This is for compatibility with existing clients that send audio in chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceStats(self, request, context):
        """Service statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyCabin(self, request, context):
        """Destroy cabin
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AllocateTranslationPort': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocateTranslationPort,
                    request_deserializer=audio__pb2.PortRequest.FromString,
                    response_serializer=audio__pb2.PortReply.SerializeToString,
            ),
            'CreateTranslationProduce': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTranslationProduce,
                    request_deserializer=audio__pb2.CreateTranslationCabinRequest.FromString,
                    response_serializer=audio__pb2.CreateTranslationCabinResponse.SerializeToString,
            ),
            'ProcessAudioBuffer': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessAudioBuffer,
                    request_deserializer=audio__pb2.ProcessAudioBufferRequest.FromString,
                    response_serializer=audio__pb2.ProcessAudioBufferResponse.SerializeToString,
            ),
            'ProcessAudioChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessAudioChunk,
                    request_deserializer=audio__pb2.ProcessAudioRequest.FromString,
                    response_serializer=audio__pb2.ProcessAudioResponse.SerializeToString,
            ),
            'GetServiceStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceStats,
                    request_deserializer=audio__pb2.Empty.FromString,
                    response_serializer=audio__pb2.ServiceStatsResponse.SerializeToString,
            ),
            'DestroyCabin': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyCabin,
                    request_deserializer=audio__pb2.DestroyCabinRequest.FromString,
                    response_serializer=audio__pb2.DestroyCabinResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audio.AudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('audio.AudioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AllocateTranslationPort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audio.AudioService/AllocateTranslationPort',
            audio__pb2.PortRequest.SerializeToString,
            audio__pb2.PortReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTranslationProduce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audio.AudioService/CreateTranslationProduce',
            audio__pb2.CreateTranslationCabinRequest.SerializeToString,
            audio__pb2.CreateTranslationCabinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessAudioBuffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audio.AudioService/ProcessAudioBuffer',
            audio__pb2.ProcessAudioBufferRequest.SerializeToString,
            audio__pb2.ProcessAudioBufferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessAudioChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audio.AudioService/ProcessAudioChunk',
            audio__pb2.ProcessAudioRequest.SerializeToString,
            audio__pb2.ProcessAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audio.AudioService/GetServiceStats',
            audio__pb2.Empty.SerializeToString,
            audio__pb2.ServiceStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyCabin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audio.AudioService/DestroyCabin',
            audio__pb2.DestroyCabinRequest.SerializeToString,
            audio__pb2.DestroyCabinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
